version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./go.dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@database:5432/madb
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: madb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
